[dataset]
function = "x*x"
xmin = -100
xmax = 100
n = 100

[mcts]
num_simulations = 1500
scorer = "UCB1"
loss_fn = "NRMSD"
leaf_picker = "recursive_heuristic_child_picker<UCB1>"
early_term_thresh = 1.999
depth_limit = 10
top_N = 100

[actions]
binary = ["addition", "subtraction", "multiplication", "division", "exponentiation"] 
unary = ["negate"]
functions = []
vars = ["x"]
scalar_min = 2
scalar_max = 5

[logging]
file = "somelog.log"

