[dataset]
function = "x^2-4*x+3"
xmin = -100
xmax = 100
n = 100

[mcts]
num_simulations = 1500
scorer = "UCB1"
loss_fn = "MAPE"
leaf_picker = "recursive_heuristic_child_picker<UCB1>"
early_term_thresh = 0.999
depth_limit = 10
top_N = 10
use_numerical_derivative = true

[actions]
binary = ["addition", "subtraction", "multiplication", "division", "exponentiation"] 
unary = ["negate"]
functions = []
vars = ["x"]
scalar_min = 1
scalar_max = 5

[logging]
file = "somelog.log"

