[dataset]
function = "_x0*_x0*_x0"
xmin = -100
xmax = 100
n = 100

[mcts]
num_simulations = 1000
scorer = "UCB1"
loss_fn = "MAPE"
leaf_picker = "recursive_heuristic_child_picker<UCB1>"
early_term_thresh = 0.999
depth_limit = 10

[actions]
binary = ["addition", "subtraction", "multiplication", "division"] 
unary = ["negate"]
functions = []
vars = ["_x0"]
scalar_min = 2
scalar_max = 4

[logging]
file = "somelog.log"

