[dataset]
function = "x^2+3*x"
xmin = -300
xmax = 300
n = 300

[mcts]
num_simulations = 2000
scorer = "UCB1"
loss_fn = "NRMSD"
leaf_picker = "recursive_heuristic_child_picker<UCB1>"
early_term_thresh = 1
depth_limit = 9
top_N = 10

[actions]
binary = ["addition", "subtraction", "multiplication", "division", "exponentiation"] 
unary = ["negate"]
functions = []
vars = ["x"]
scalar_min = 2
scalar_max = 4

[logging]
file = "somelog.log"

